name: Reusable Workflow to print out timestamp

on:
  workflow_call:

jobs:
  timestamp:
    runs-on: ubuntu-latest
    steps:

      - name: Generate timestamp
        run: |
          echo "TIMESTAMP=$(TZ='America/Los_Angeles' date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Print timestamp
        run: |
          echo "Execution time (Pacific Time Zone) $TIMESTAMP"
