name: Reusable TruffleHog Scan

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      depth:
        required: false
        type: number
        default: 2
    secrets:
      SLACK_BOT_TOKEN:
        required: false
      SLACK_CHANNEL_ID_GITHUB_NOTIFICATION:
        required: false

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  SecurityScan:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ inputs.branch }}
      DEPTH: ${{ inputs.depth }}
    steps:

      - name: Checkout the repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b #v4.1.4
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: ${{ env.DEPTH }}

      - name: Run TruffleHog Scan
        uses: trufflesecurity/trufflehog@4ea3a1376b709cebb6a5c7b664693fe733bd43f5 #v3.75.0
        with:
          extra_args: --only-verified

      - name: Check for Slack configuration
        if: failure()
        id: slack-check
        run: |
          if [ -n "${{ secrets.SLACK_BOT_TOKEN }}" ] && [ -n "${{ secrets.SLACK_CHANNEL_ID_GITHUB_NOTIFICATION }}" ]; then
            echo "slack-configured=true" >> $GITHUB_OUTPUT
          else
            echo "slack-configured=false" >> $GITHUB_OUTPUT
          fi

      - name: Send notification to slack if secrets found
        if: failure() && steps.slack-check.outputs.slack-configured == 'true'
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID_GITHUB_NOTIFICATION }}
          payload: |
            {
              "text": "TruffleHog scan detected secrets in ${{
                github.repository }}. Please review the action logs.",
              "blocks": [
                { "type": "divider" },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🚨 *Alert:* TruffleHog detected secrets in ${{
                      github.repository }}. [View details](https://github.com/${{
                      github.repository }}/actions/runs/${{ github.run_id }})"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Log secrets detection without Slack
        if: failure() && steps.slack-check.outputs.slack-configured == 'false'
        run: |
          echo "🚨 TruffleHog detected secrets in the repository!"
          echo "Please review the scan results above and remediate any exposed secrets."
          echo "Note: Slack notification is not configured. Set SLACK_BOT_TOKEN and SLACK_CHANNEL_ID_GITHUB_NOTIFICATION secrets to enable notifications."
