name: Reusable Lint Workflow

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Go version'
        required: true
        default: '1.22'
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ inputs.go-version }}

      - name: Run Linter
        run: |
          echo "Running golangci-lint"
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run
