name: Reusable Workflow to print out timestamp

on:
  workflow_call:
    inputs:
      timezone:
        description: 'Timezone to use for timestamp'
        required: false
        type: string
        default: 'America/Los_Angeles'

jobs:
  timestamp:
    runs-on: ubuntu-latest
    steps:

      - name: Generate timestamp
        run: |
          echo "TIMESTAMP=$(TZ=${{ inputs.timezone }} date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

      - name: Print timestamp
        run: |
          echo "Execution time (Pacific Time Zone) $TIMESTAMP"
